### ISSUE TITLE
wandb logging does not seem to work (on Colab at least)

### ISSUE THREAD

**Issue by Guthman** [manujosephv/pytorch_tabular#24] opened 2021-06-17 17:04 UTC
I could be misunderstanding how the logging works, but I can't get it to work. I define my experiment_config with:

```
experiment_config = ExperimentConfig(
    project_name='some_project, 
    log_target='wandb',
    exp_watch='gradients',
    log_logits=False)
```
(side note: passing 'all' to `exp_watch` leads to an error*, and passing 'True' to `log_logits` does so as well**)

I then pass the config to the model, like so:

```
tabular_model = TabularModel(data_config=data_config, 
                             model_config=model_config,
                             optimizer_config=optimizer_config,
                             trainer_config=trainer_config,
                             experiment_config=experiment_config)
```

The big thing I'm missing is how does the trainer know what wandb account to log to? There's no way to pass a wandb API key as far as I can tell, the docs don't mention anything. I can see that wandb logs are created locally, but I've no clue if they're actually being sent anywhere and where to find them if that's case.

*Using `exp_watch='all'` leads to:
`RuntimeError: _th_histc not supported on CPUType for Byte`

and

```
MisconfigurationException: ModelCheckpoint(monitor='valid_loss') not found in the returned metrics: ['train_loss']. HINT: Did you call self.log('valid_loss', tensor) in the LightningModule?
```
Traceback: [exp_watch(all).txt](https://github.com/manujosephv/pytorch_tabular/files/6671916/exp_watch.all.txt)

**Using `log_logits=True` leads to:
`IndexError: index 1 is out of bounds for dimension 1 with size 1`
Traceback: [log_logits(True).txt](https://github.com/manujosephv/pytorch_tabular/files/6671915/log_logits.True.txt) 
Could it maybe be necessary to one-hot encode the target column to use this function?

The target column is of dtype int64

**Comment by manujosephv** [comment] 2021-06-20 12:06
Quite a lot to unpack here.

1. How does the Trainer know what wandb account to log in to?  - A very good question. I hadn't really thought of it before. Ideally, if you have used wandb at least once in your machine, it should work. But for the first time user, think you need to login to your account with wandb --> either do `wandb login` from command prompt, or use `wandb.login()` in python. In colab and other interactive IDEs, I've also seen wandb ask for the login auth as an interactive step.
2.  passing 'all' to exp_watch leads to an error*, and passing 'True' to log_logits does so as well --> This should not cause an error. If you are able to send me a reproducible example, I can take a look at the issue.
3. Could it maybe be necessary to one-hot encode the target column to use this function? - No. Cause all of that is handled inside the models. But I've seen weird behavior with batch size =1. If you can send me a reproducible code, I can take a look.

**Comment by manujosephv** [comment] 2021-09-01 12:21
closing this because of non-response. Feel free to reopen if you have new information.

**Closed by manujosephv** 2021-09-01 12:21 UTC

**Comment by HernandoR** [comment] 2024-03-12 02:58
enconter `log_logits=true` causing error, my guess is some error on the shape of dfs, not easy to construct an Minimal Example but ill try.
```logs
File [/opt/homebrew/Caskroom/miniforge/base/envs/AMEX/lib/python3.11/site-packages/pytorch_tabular/models/base_model.py:525], in BaseModel.create_plotly_histogram(self, arr, name, bin_dict)
[521] fig = go.Figure()
[522] for i in range(arr.shape[-1]):
[523]     fig.add_trace(
[524]         go.Histogram(
--> [525]             x=arr[:, i],
[526]             histnorm="probability",
[527]             name=f"{name}_{i}",
[528]             xbins=bin_dict,  # dict(start=0.0, end=1.0, size=0.1),  # bins used for histogram
[529]         )
[530]     )
[531] # Overlay both histograms
[532] fig.update_layout(
[533]     barmode="overlay",
[534]     legend={"orientation": "h", "yanchor": "bottom", "y": 1.02, "xanchor": "right", "x": 1},
[535] )
```

also enconter
```
Can't pickle <function TorchGraph.create_forward_hook.<locals>.after_forward_hook at 0x37f1bcf40>: it's not found as wandb.wandb_torch.TorchGraph.create_forward_hook.<locals>.after_forward_hook
```
when save model with `log_target=wandb`
